apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::381437929435:role/eksctl-login-cluster-nodegroup-lin-NodeInstanceRole-8qh8X3sFNJrV
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::381437929435:role/instanverole1
      groups:
      - system:masters
      username: ec2-user
  mapUsers: |
    - userarn: arn:aws:iam::381437929435:user/devops-admin
      groups:
      - system:masters
      username: devops-admin
    - userarn: arn:aws:iam::381437929435:user/jenkins-user
      groups:
      - system:masters
      username: jenkins-user
