apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-account
  annotations:
    # REPLACE with your actual IAM Role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::381437929435:role/instanverole1
---
